apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  - port: 5000
    name: client
  selector:
    app: client
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: youtube-downloader-client
        image: youtube-downloader-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: REACT_APP_SOCKET_URL
          value: http://192.168.39.84:31879
